/**
 * @file Eleventy configuration file.
 * @license zlib
 */

// @ts-check

import path from "node:path";
import webc from "@11ty/eleventy-plugin-webc";
import externalLinks from "@aloskutov/eleventy-plugin-external-links";
import browserslist from "browserslist";
import { compress } from "eleventy-plugin-compress";
import htmlmin from "html-minifier-next";
import { browserslistToTargets, bundle } from "lightningcss";

// Configures browserslist targets.
const targets = browserslistToTargets(browserslist("> 0.2% and not dead"));

// Globally used site metadata.
const siteData = {
	color: "#ffaa00",
	description: "Blind developer, tinkerer, and activist from North Alabama.",
	title: "Espi Marisa",
	url: "https://espi.me",
};

export default async function (eleventyConfig) {
	// Configures data, input, and output directories.
	eleventyConfig.setInputDirectory("./src");
	eleventyConfig.setOutputDirectory("./_site");
	eleventyConfig.setDataDirectory("_data");
	eleventyConfig.setIncludesDirectory("_includes");
	eleventyConfig.setLayoutsDirectory("_layouts");

	// Copy static files in /public to the root output directory.
	eleventyConfig.addPassthroughCopy({ "./public": "/" });

	// Enables WebC support.
	eleventyConfig.addPlugin(webc);

	// Automatically append target=_blank and rel attributes to external links.
	eleventyConfig.addPlugin(externalLinks, {
		excludedDomains: siteData.url,
	});

	// Automatically compress contents with brotli.
	eleventyConfig.addPlugin(compress, {
		algorithm: "brotli",
		enabled: true,
	});

	// Process CSS with LightningCSS.
	eleventyConfig.addTemplateFormats(["css", "webc"]);
	eleventyConfig.addExtension("css", {
		outputFileExtension: "css",

		// Compiles the content.
		compile: async (_content, input) => {
			// Parses the content; ignore files starting with _.
			const parsed = path.parse(input);
			if (parsed.name.startsWith("_")) {
				return;
			}

			return async () => {
				// Bundles the content together.
				const { code } = bundle({
					filename: input,
					minify: true,
					sourceMap: false,
					targets: targets,
				});

				return code;
			};
		},
	});

	// Minifies HTML contents.
	eleventyConfig.addTransform("htmlmin", function (content) {
		// Only minify pages processed as HTML templates.
		if ((this.page.outputPath || "").endsWith(".html")) {
			const minified = htmlmin.minify(content, {
				collapseBooleanAttributes: true,
				collapseInlineTagWhitespace: true,
				collapseWhitespace: true,
				conservativeCollapse: true,
				decodeEntities: true,
				includeAutoGeneratedTags: false,
				minifyCSS: true,
				minifyJS: true,
				minifyURLs: true,
				noNewlinesBeforeTagClose: true,
				preventAttributesEscaping: true,
				processConditionalComments: true,
				removeAttributeQuotes: true,
				removeComments: true,
				removeEmptyAttributes: true,
				removeOptionalTags: true,
				removeRedundantAttributes: true,
				removeScriptTypeAttributes: true,
				removeStyleLinkTypeAttributes: true,
				sortAttributes: true,
				sortClassName: true,
				trimCustomFragments: true,
				useShortDoctype: true,
			});

			return minified;
		}

		return content;
	});
}
