import postcssPlugin from "@jgarber/eleventy-plugin-postcss";
import eleventyPluginTinyHTML from "@sardine/eleventy-plugin-tinyhtml";
import automaticNoopener from "eleventy-plugin-automatic-noopener";

/** @param {import("@11ty/eleventy").UserConfig} eleventyConfig */
// biome-ignore lint/style/noDefaultExport: Eleventy requires a default export.
export default async function (eleventyConfig) {
  // Directories
  eleventyConfig.setInputDirectory("./src");
  eleventyConfig.setOutputDirectory("./_site");
  eleventyConfig.setLayoutsDirectory("_layouts");
  eleventyConfig.setIncludesDirectory("_includes");
  eleventyConfig.addPassthroughCopy("./src/css");
  eleventyConfig.addPassthroughCopy("./src/img");

  // nasty fix for fonts
  eleventyConfig.addPassthroughCopy({
    "./node_modules/@fontsource/atkinson-hyperlegible/files/*.woff2":
      "css/files",
  });

  // Sets Liquid options
  eleventyConfig.setLiquidOptions({
    dynamicPartials: false,
    strictFilters: true,
  });

  // Date formatter filter
  eleventyConfig.addFilter("postDate", (dateObj) => {
    return dateObj.toLocaleString(undefined, {
      year: "numeric",
      month: "numeric",
      day: "numeric",
    });
  });

  // Alphabetically sort webring
  eleventyConfig.addCollection("webring", (collection) =>
    collection.getFilteredByGlob("./src/_webring/*.md").sort((a, b) => {
      if (a.data.title > b.data.title) {
        return 1;
      }

      if (a.data.title < b.data.title) {
        return -1;
      }

      return 0;
    }),
  );
  // PostCSS support
  eleventyConfig.addPlugin(postcssPlugin);

  // Automatically append nooopeners
  eleventyConfig.addPlugin(automaticNoopener);

  // Minify HTTML
  eleventyConfig.addPlugin(eleventyPluginTinyHTML, {
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: true,
    collapseWhitespace: true,
    conservativeCollapse: true,
    decodeEntities: true,
    includeAutoGeneratedTags: false,
    minifyCSS: true,
    minifyJS: true,
    minifyURLs: true,
    preventAttributesEscaping: true,
    processConditionalComments: true,
    removeAttributeQuotes: false,
    removeComments: true,
    removeEmptyAttributes: true,
    removeOptionalTags: true,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    sortAttributes: true,
    sortClassName: true,
    trimCustomFragments: true,
    useShortDoctype: true,
  });
}
