name: "Push Testing"

on:
  push:
    branches: ["main"]

jobs:
  build-and-test:
    permissions:
      actions: write
      checks: write
      contents: read
      deployments: read
      issues: write
      pull-requests: write
      security-events: write
      statuses: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run test
